apiVersion: v1
kind: ServiceAccount
metadata:
  name: shellshock
  app: shellshock
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shellshock
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: shellshock
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shellshock
  labels:
    app: shellshock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shellshock
  template:
    metadata:
      labels:
        app: shellshock
    spec:
      containers:
      - name: shellshock
        imagePullPolicy: IfNotPresent
        image: quay.io/apoczeka/shellshock:latest
        ports:
        - containerPort: 8080
        - containerPort: 8443
      serviceAccount: shellshock
      securityContext:
        runAsUser: 48
        runAsGroup: 0
---
apiVersion: v1
kind: Service
metadata:
  name: shellshock
  labels:
    app: shellshock
spec:
  selector:
    app: shellshock
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: shellshock
  name: shellshock
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: shellshock
  wildcardPolicy: None

